# frozen_string_literal: true

require "minitest/autorun"

require_relative "../app/models/board"
require_relative "../app/models/map_config"
require_relative "../app/models/player"
require_relative "../app/weapons/basic_shot"
require_relative "../app/weapons/missile"
require_relative "../app/weapons/airplane"
require_relative "../app/controllers/attack_handler"
require_relative "../app/turn_strategies/turn_strategy"
require_relative "../app/turn_strategies/single_shot"
require_relative "../app/turn_strategies/extra_shot_on_hit"
require_relative "../app/turn_strategies/factory"
require_relative "../app/ai/random_ai"
require_relative "../app/game"
require_relative "../app/controllers/game_controller"
require_relative "../app/services/score_calculator"
require_relative "../app/services/database"
